name: Generate macOS Installer

on:
  workflow_dispatch:
    inputs:
      macos_version:
        type: choice
        description: "macOS Version"
        required: true
        options:
          - Sonoma v14.5
          - Ventura v13.6.7
          - Monterey v12.7.5
      file:
        type: choice
        description: "File Type"
        required: true
        options:
          - ISO
          - DMG
          - ZIP

run-name: Generate macOS Installer - ${{ github.event.inputs.macos_version }} ${{ github.event.inputs.file }}

env:
  installer_version: ""
  installer_name: ""

jobs:
  build:
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v4

      - name: Extract Version Details
        id: extract-details
        run: |
          string="${{ github.event.inputs.macos_version }}"
          echo "installer_version=${string//*v/}" >> $GITHUB_ENV
          echo "installer_name=${string// v*/}" >> $GITHUB_ENV

      - name: Download macOS Installer
        run: |
          softwareupdate --fetch-full-installer --full-installer-version ${{ env.installer_version }}

      - if: ${{ github.event.inputs.file == 'DMG' }}
        name: Generate macOS DMG Installer
        run: |
          sudo hdiutil create -o /tmp/'${{ env.installer_name }}' -size 16384m -volname '${{ env.installer_name }}' -layout SPUD -fs HFS+J
          sudo hdiutil attach /tmp/'${{ env.installer_name }}'.dmg -noverify -mountpoint /Volumes/'${{ env.installer_name }}'
          sleep 10
          sudo /Applications/'Install macOS ${{ env.installer_name }}'.app/Contents/Resources/createinstallmedia --volume /Volumes/'${{ env.installer_name }}' --nointeraction
          hdiutil eject -force /Volumes/'Install macOS ${{ env.installer_name }}'
          sudo mv /tmp/'${{ env.installer_name }}'.dmg $HOME/Desktop/'${{ env.installer_name }}'.dmg

      - if: ${{ github.event.inputs.file == 'ISO' }}
        name: Generate macOS ISO Installer
        run: |
          sudo hdiutil create -o /tmp/'${{ env.installer_name }}' -size 16384m -volname '${{ env.installer_name }}' -layout SPUD -fs HFS+J
          sudo hdiutil attach /tmp/'${{ env.installer_name }}'.dmg -noverify -mountpoint /Volumes/'${{ env.installer_name }}'
          sleep 20
          sudo /Applications/'Install macOS ${{ env.installer_name }}'.app/Contents/Resources/createinstallmedia --volume /Volumes/'${{ env.installer_name }}' --nointeraction
          sleep 100
          hdiutil eject -force /Volumes/'Install macOS ${{ env.installer_name }}'
          hdiutil convert /tmp/'${{ env.installer_name }}'.dmg -format UDTO -o $HOME/Desktop/'${{ env.installer_name }}'
          mv -v $HOME/Desktop/'${{ env.installer_name }}'.cdr $HOME/Desktop/'${{ env.installer_name }}'.iso
          sudo rm -fv /tmp/'${{ env.installer_name }}'.dmg

      - if: ${{ github.event.inputs.file == 'ZIP' }}
        name: Generate macOS ZIP Installer
        run: |
          cd /Applications
          zip -r 'Install macOS ${{ env.installer_name }}.zip' 'Install macOS ${{ env.installer_name }}.app'
          mv -v 'Install macOS ${{ env.installer_name }}.zip' $HOME/Desktop/'${{ env.installer_name }}.zip'

      - name: Upload Installer
        uses: actions/upload-artifact@v4
        with:
          name: macOS ${{ env.installer_name }}
          path: "${{ env.HOME }}/Desktop/${{ env.installer_name }}.${{ github.event.inputs.file }}"
